---
abstract: 'Per request clone of a DBIC model with additional parameters'
author:
  - 'Roman F. <romanf@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Runtime: 5.80
  Catalyst::Test: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  Test::Exception: 0
  Test::More: 0
  base: 0
  lib::abs: 0
  namespace::autoclean: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-DBIC-Schema-PerRequest
requires:
  Carp: 0
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Model: 0
  Module::Runtime: 0
  Moose: 0
  strict: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Model-DBIC-Schema-PerRequest
  repository: git://github.com/moltar/Catalyst-Model-DBIC-Schema-PerRequest.git
version: 0.002001
